apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gh-user-deployment
  labels:
    app: gh-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gh-user
  template:
    metadata:
      labels:
        app: gh-user
    spec:
      containers:
      - name: gh-user
        image: chrispcode/gh-user:v5
        env:
        - name: SERVICE_PORT
          value: "80"
        - name: DB_HOST
          value: rethinkdb-access-svc
        - name: DB_NAME
          value: GroundHall
        - name: DB_TABLE_NAME
          value: Users
        - name: SECRET_TOKEN
          valueFrom:
              secretKeyRef:
                name: inhouse
                key: token
        ports:
        - containerPort: 80