apiVersion: v1
kind: Service
metadata:
  name: "gh-port-graphql-svc"
spec:
  type: LoadBalancer
  selector:
    app: gh-port-graphql
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
